networks:
  app-network:
    driver: bridge

services:
  template:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_IS_DOCKER=dockercompose
      - VITE_ENV=staging
      - VITE_API_URL=http://localhost:3000
      - VITE_APP_NAME="React Template"
      - VITE_APP_STORAGE_PREFIX=template
