networks:
  app-network:
    driver: bridge

services:
  template:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - app-network
    environment:
      - VITE_IS_DOCKER=true
      - VITE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_APP_NAME="React Template"
      - VITE_APP_STORAGE_PREFIX=template
